name: OpenCV-Course
channels:
  - conda-forge
  - quantstack
dependencies:
  - python==3.6
  - numpy==1.15.4
  - scipy==1.1.0
  - scikit-learn==0.20.1
  - matplotlib
  - jupyter==1.0
  - notebook==5.7.4
  - pandas==0.23.4
  - scikit-image
  - keras==2.2.4
  - mkl-service==1.1.2
  - xeus-cling
  - nbgrader
  - pip
  - pip:
    - wheel
    - cmake
    - dlib
    - opencv-contrib-python==4.0.0.21
